Hw 2
PavelPlotnikov25/NIX_11 pull request #2
Opened 2022-07-08 13:25 UTC by PavelPlotnikov25

add tests

2022-07-08 22:45 UTC, Fabolo12 requested changes
Все хорошо, но не вижу примеров по пунктам
ArgumentMatchers 
Calling real methods

2022-07-11 22:08 UTC, Fabolo12 approved these changes

2022-07-11 22:08 UTC, Fabolo12 commented on src/test/java/com/service/TelevisionServiceTest.java
> +        Assertions.assertThrows(NullPointerException.class, () -> target.getAll());
А почему тут NullPointerException ты понимаешь?)

2022-07-12 08:06 UTC, PavelPlotnikov25 commented on src/test/java/com/service/TelevisionServiceTest.java
> +        Assertions.assertThrows(NullPointerException.class, () -> target.getAll());
похоже потому что при моке, не отрабатывает конструктор репозитория)

2022-07-14 13:40 UTC, merged